function h = panelStatSTEM(h,img)
%% Create the StatSTEM logo panel using native MATLAB (replaces Java/im2java)

% Create a uipanel to hold the logo
hh = uipanel('Parent', h.left.main, ...
             'Units', 'normalized', ...
             'Position', [0 0.1 1 0.35], ...
             'BorderType', 'none', ...
             'BackgroundColor', [0.95 0.95 0.95]);

% Display the image in an axes filling the panel
ax = axes('Parent', hh, ...
          'Units', 'normalized', ...
          'Position', [0 0 1 1], ...
          'Visible', 'off');
imshow(img, 'Parent', ax);

h.left.StatSTEM.panel  = hh;
h.left.StatSTEM.jpanel = hh;  % keep same field name for compatibility