function [hPb, hContainer] = createProgressbar(parent, position)
% createProgressbar - Create a native MATLAB progressbar
%--------------------------------------------------------------------------

% Outer container (grey background)
hContainer = uipanel('Parent', parent, ...
                     'Units', 'normalized', ...
                     'Position', position, ...
                     'BorderType', 'none', ...
                     'BackgroundColor', [0.8 0.8 0.8]);

% Single blue fill panel - title shows percentage
fillPanel = uipanel('Parent', hContainer, ...
                    'Units', 'normalized', ...
                    'Position', [0 0 0 1], ...
                    'BorderType', 'none', ...
                    'BackgroundColor', [0.2 0.6 1], ...
                    'Title', '', ...
                    'FontWeight', 'bold', ...
                    'FontSize', 9);

hPb = StatSTEMProgressBar(hContainer, fillPanel, fillPanel);